module.exports = {
  extends: [
    "plugin:@typescript-eslint/recommended",
    "@react-native-community",
    "plugin:import/recommended",
    "plugin:import/typescript",
  ],
  parser: "@typescript-eslint/parser",
  plugins: ["import"],
  rules: {
    "react-native/no-unused-styles": "error",
    "import/exports-last": "error",
    "import/first": "error",
    "import/group-exports": "error",
    "import/newline-after-import": "error",
    "import/no-absolute-path": "error",
    "import/no-self-import": "error",
    "import/no-useless-path-segments": ["error", { noUselessIndex: true }],
    "import/no-duplicates": "error",
    "import/order": [
      "error",
      {
        alphabetize: { order: "asc" },
        "newlines-between": "always",
        pathGroups: [
          {
            group: "parent",
            pattern: "~/**",
            position: "before",
          },
        ],
      },
    ],
    "import/no-cycle": ["warn", { ignoreExternal: true }],
    "import/no-dynamic-require": "warn",
    "import/no-extraneous-dependencies": "warn",
    "import/no-mutable-exports": "warn",
    "import/no-unassigned-import": "warn",
    "no-undefined": "warn",
    "no-console": "warn",
    "import/no-deprecated": "off",
    "import/no-unresolved": "off",
    "import/namespace": "off",
    "import/default": "off",
    "import/named": "off",
    "import/no-named-as-default-member": "off",
    "import/no-named-as-default": "off",
    "import/no-unused-modules": "off",
  },
};
